### PR TITLE
Track LFS files in .gitattributes

### PR DESCRIPTION
**Pull request by thearst3rd**
Currently in this repository, LFS-tracked files need to be managed manually with commands like `git lfs pull`, which also causes the git repository to register 2000+ files as "changed" when executed. LFS should be seamless and work transparently with existing workflows.

This pull requests adds a .gitattributes file which tracks all ".dds" files (which were the only files in LFS). That one line also caused 21 addition .dds files to be tracked which were missed before.

### CODE REVIEW

**Comment by RandomityGuy** [comment]
Earlier, LFS files were tracked by this method but we exceeded the github LFS free limits hence I stopped LFS from storing newer files. But it kept the older files in the LFS.

**Comment by HiGuyMB** [comment]
For reference, the original repo had ~1GB of files in LFS which meant that every single clone would exceed Github's bandwidth limit. We used to host this privately where LFS limits were not a problem, but Github's offering for it is basically unusable. If anything, this repo should take all the files out of LFS and just serve them straight. It is not better for git performance but it's better on the wallet.

**Comment by thearst3rd** [comment]
https://stackoverflow.com/questions/40365154/git-migrate-from-lfs-to-normal-repo

Found this potential solution to migrate everything out of LFS, the big caveat is that it actually rewrites the entire commit history and will require all developers to discard their branches and pull again. So if we do this, we need to make sure that all developers are aware of what it'll do.

```
/d/My Games/PlatinumQuest-Dev (dev) % git lfs migrate info --everything
migrate: Sorting commits: ..., done.
migrate: Examining commits: 100% (1196/1196), done.
*.png           616 MB  4844/4844 files 100%
*.dif           615 MB  3981/3981 files 100%
*.JPG           280 MB    919/919 files 100%
*.wav           222 MB    541/541 files 100%
*.jpg           206 MB  4593/4593 files 100%

LFS Objects     1.8 GB  3019/3019 files 100%
```

That looks like the number of files we're dealing with.

If all we care about are files in the current head, then this might also work, we could do this on the dev branch: https://stackoverflow.com/questions/35011366/move-git-lfs-tracked-files-under-regular-git

I'll admit I'm not very familiar with LFS so I have question - if we were hitting clone bandwidth limits of 1GB on every clone, and those files were _already in LFS_ meaning they weren't downloaded unless they were needed, then how would moving all these files out into normal history help with that? I may just be misunderstanding.

**Comment by thearst3rd** [comment]
I'll close this PR. Whatever the issue was, it stopped happening a while back

**Pull request closed without merging**
